name: Track Clones
on: push

jobs:
  test: 
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - name: Set up Python version
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          pip3 install PyGithub
          python -m pip install --upgrade pip pandas
      - name: Run fetch.py
        env: 
          SECRET_TOKEN: ${{ secrets.SECRET_TOKEN }}
        run: python fetch.py j0ycehe/artoftheweb
      - name: Commit download statistics
        run: |
          git config --global user.name 'j0ycehe'
          git config --global user.email 'joycehe@sas.upenn.edu'
          git add -A
          git diff-index --quiet HEAD || (git commit -a -m "Update download statistics" --allow-empty)
      - name: Push download statistics
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main 

