name: Track Clones
on: 
  schedule:
      # Run this once per day, towards the end of the day for keeping the most
      # recent data point most meaningful (hours are interpreted in UTC).
      - cron: "0 23 * * *"
  workflow_dispatch: # Allow for running this manually.
permissions:
  contents: write
jobs:
  track_clones: 
    strategy: 
      matrix:
        repo: [j0ycehe/artoftheweb, j0ycehe/j0ycehe.github.io]
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v3
      - name: Set up Python version
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          pip3 install PyGithub
          python -m pip install --upgrade pip pandas
      - name: Run fetch.py
        env: 
          SECRET_TOKEN: ${{ secrets.SECRET_TOKEN }}
        run: python fetch.py ${{ matrix.repo }}
      - name: Commit download statistics
        run: |
          git config --global user.name 'j0ycehe'
          git config --global user.email 'joycehe@sas.upenn.edu'
          git add -A
          git commit -am "Update download statistics"
      - name: Push download statistics
        run: git push

