name: Track Clones

on: push

jobs:
  test: 
    runs-on: ubuntu-latest
    steps: 
      - run: echo $REPO
        env: 
          REPO: ${{ github.repository }}
      - name: run test.py
        run: python ${{ github.repository }} test.py j0ycehe/artoftheweb
